development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: bug_tracker_development
  pool: 5
  username: postgres
  password: prakruthi
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: bug_tracker_test
  pool: 5
  username: postgres
  password: prakruthi
  host: localhost
  port: 5432
