it:
  adapter: postgresql
  encoding: unicode
  database: bugtrackers_it
  pool: 10
  username: postgres
  password: password
  host: localhost
  port: 5432

development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: bug_trackers_development
  pool: 5
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: bug_trackers_test
  pool: 5
  username: postgres
  password: prakruthi
  host: localhost
  port: 5432